version: '2'
services:
  xnat-web:
    build:
      context: ./xnat
      args:
        XNAT_VER: ${XNAT_VER}
        XNAT_PIPELINE_ENGINE_VER: ${XNAT_PIPELINE_ENGINE_VER}
        SNET_PLUGIN_VER: ${SNET_PLUGIN_VER}
        SNET_PIPELINES_VER: ${SNET_PIPELINES_VER}
        XNAT_DATASOURCE_DRIVER: ${XNAT_DATASOURCE_DRIVER}
        XNAT_DATASOURCE_URL: ${XNAT_DATASOURCE_URL}
        XNAT_DATASOURCE_USERNAME: ${XNAT_DATASOURCE_USERNAME}
        XNAT_DATASOURCE_PASSWORD: ${XNAT_DATASOURCE_PASSWORD}
        XNAT_HIBERNATE_DIALECT: ${XNAT_HIBERNATE_DIALECT}
        TOMCAT_XNAT_FOLDER: ${TOMCAT_XNAT_FOLDER}
        XNAT_ROOT: ${XNAT_ROOT}
        XNAT_HOME: ${XNAT_HOME}

    ports:
      - "8081:8080"
      - "8000:8000"
      - "1337:22"
    volumes:
      # - ./xnat/plugins:/data/xnat/home/plugins
      # - ../xnat-pipeline-engine:/tmp/xnat-pipeline-engine
      # - ../snet-pipelines:/tmp/snet-pipelines
      - ./xnat-data/home/logs:/data/xnat/home/logs
      - ./xnat-data/archive:/data/xnat/archive
      - ./xnat-data/build:/data/xnat/build
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db
    environment:
      - CATALINA_OPTS=-Xms128m -Xmx2048m -Dxnat.home=/data/xnat/home -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
      - XNAT_HOME=${XNAT_HOME}
      - PGPASSWORD=${XNAT_DATASOURCE_PASSWORD}

  xnat-db:
    build: ./postgres
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${XNAT_DATASOURCE_ADMIN_PASSWORD}
  xnat-nginx:
    build:
      context: ./nginx
      args:
        COPLA_EDITOR_VER: ${COPLA_EDITOR_VER}
    ports:
      - "80:80"
    expose:
      - "80"
    links:
      - xnat-web
    # volumes:
      # - ../copla-editor/sn-editor/build:/var/www/copla-editor

  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
  #   command:
  #     - '-config.file=/etc/prometheus/prometheus.yaml'
  #   ports:
  #     - '9090:9090'
  #   links:
  #     - cadvisor
  #
  # cadvisor:
  #   image: google/cadvisor
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   ports:
  #     - "8082:8080"
  #   expose:
  #     - 8082
