version: '3'
services:
  xnat-web:
    build:
      context: ./xnat
      args:
        XNAT_VER: ${XNAT_VER}
        XNAT_PIPELINE_ENGINE_VER: ${XNAT_PIPELINE_ENGINE_VER}
        SNET_PLUGIN_VER: ${SNET_PLUGIN_VER}
        SNET_PIPELINES_VER: ${SNET_PIPELINES_VER}
        XNAT_DATASOURCE_DRIVER: ${XNAT_DATASOURCE_DRIVER}
        XNAT_DATASOURCE_URL: ${XNAT_DATASOURCE_URL}
        XNAT_DATASOURCE_USERNAME: ${XNAT_DATASOURCE_USERNAME}
        XNAT_DATASOURCE_PASSWORD: ${XNAT_DATASOURCE_PASSWORD}
        XNAT_HIBERNATE_DIALECT: ${XNAT_HIBERNATE_DIALECT}
        TOMCAT_XNAT_FOLDER: ${TOMCAT_XNAT_FOLDER}
        XNAT_ROOT: ${XNAT_ROOT}
        XNAT_HOME: ${XNAT_HOME}
    ports:
      - "8081:8080"
      - "8000:8000"
      - "1337:22"
    volumes:
      - ./data/xnat/home/logs:/data/xnat/home/logs
      - ./data/xnat/archive:/data/xnat/archive
      - ./data/xnat/build:/data/xnat/build
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./xnat/plugins:/data/xnat/home/plugins
      # - ../xnat-pipeline-engine:/tmp/xnat-pipeline-engine
      # - ../snet-pipelines:/tmp/snet-pipelines
    depends_on:
      - xnat-db
    environment:
      - CATALINA_OPTS=-Xms128m -Xmx2048m -Dxnat.home=/data/xnat/home -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
      - XNAT_HOME=${XNAT_HOME}
      - PGPASSWORD=${XNAT_DATASOURCE_PASSWORD}

  xnat-db:
    image: postgres:9.4-alpine
    expose:
      - "5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${XNAT_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${XNAT_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${XNAT_DATASOURCE_DBNAME}
      POSTGRES_PASSWORD: ${XNAT_DATASOURCE_PASSWORD}

  xnat-nginx:
    build:
      context: ./nginx
      args:
        COPLA_EDITOR_VER: ${COPLA_EDITOR_VER}
    ports:
      - "80:80"
    expose:
      - "80"
    links:
      - xnat-web
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      # - ../copla-editor/sn-editor/build:/var/www/copla-editor
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot